// Complete CEFR 2020 Descriptor Scales for lesson generation
// Covers all spoken/written language scales (excluding sign language)
// Each scale maps to skill tags and contains representative descriptors per level

export interface DescriptorScale {
  id: string;
  title: string;
  skill: string;
  category: string;
  descriptors: Record<string, string>;
}

export const DESCRIPTOR_SCALES: DescriptorScale[] = [
  // ===== RECEPTION: ORAL COMPREHENSION =====
  {
    id: 'overall-oral-comprehension',
    title: 'Overall Oral Comprehension',
    skill: 'listening',
    category: 'Reception',
    descriptors: {
      'Pre-A1': 'Can understand short, very simple questions and statements, provided they are delivered slowly and clearly.',
      A1: 'Can follow language which is very slow and carefully articulated, with long pauses.',
      A2: 'Can understand phrases and expressions related to areas of most immediate priority.',
      B1: 'Can understand the main points made in clear standard language on familiar matters.',
      B2: 'Can understand the main ideas of complex discourse on both concrete and abstract topics.',
      C1: 'Can follow extended discourse on abstract and complex topics beyond their field.',
      C2: 'Can understand with ease virtually any kind of language, whether live or broadcast.',
    },
  },
  {
    id: 'understanding-conversation',
    title: 'Understanding Conversation Between Others',
    skill: 'listening',
    category: 'Reception',
    descriptors: {
      A1: 'Can understand words and short sentences in a simple conversation.',
      A2: 'Can follow in outline short, simple social exchanges, conducted very slowly.',
      B1: 'Can generally follow the main points of extended discussion around them.',
      B2: 'Can catch much of what is said around them in discussion.',
      C1: 'Can easily follow complex interactions in group discussion and debate.',
      C2: 'Can identify the sociocultural implications of most colloquial language.',
    },
  },
  {
    id: 'understanding-live-audience',
    title: 'Understanding as a Member of a Live Audience',
    skill: 'listening',
    category: 'Reception',
    descriptors: {
      A1: 'Can understand in outline very simple information in a predictable situation like a guided tour.',
      A2: 'Can follow a very simple, well-structured presentation with visual support.',
      B1: 'Can follow in outline straightforward short talks on familiar topics.',
      B2: 'Can follow complex lines of argument in a clearly articulated lecture.',
      C1: 'Can follow most lectures, discussions and debates with relative ease.',
      C2: 'Can follow specialised lectures employing colloquialism or unfamiliar terminology.',
    },
  },
  {
    id: 'understanding-announcements',
    title: 'Understanding Announcements & Instructions',
    skill: 'listening',
    category: 'Reception',
    descriptors: {
      'Pre-A1': 'Can understand short, simple instructions like "Stop", accompanied by pictures or gestures.',
      A1: 'Can understand instructions addressed carefully and slowly and follow short, simple directions.',
      A2: 'Can catch the main point in short, clear, simple messages and announcements.',
      B1: 'Can understand simple technical information for everyday equipment.',
      B2: 'Can understand announcements on concrete and abstract topics at normal speed.',
      C1: 'Can extract specific information from poor quality public announcements.',
    },
  },
  {
    id: 'understanding-audio-media',
    title: 'Understanding Audio Media & Recordings',
    skill: 'listening',
    category: 'Reception',
    descriptors: {
      A1: 'Can pick out concrete information from short recordings on everyday topics.',
      A2: 'Can understand and extract essential information from short recorded passages.',
      B1: 'Can understand the main points of news bulletins and simpler recorded material.',
      B2: 'Can understand most documentaries and broadcast material in standard language.',
      C1: 'Can understand a wide range of recorded material, including non-standard usage.',
    },
  },
  // ===== RECEPTION: READING COMPREHENSION =====
  {
    id: 'overall-reading',
    title: 'Overall Reading Comprehension',
    skill: 'reading',
    category: 'Reception',
    descriptors: {
      'Pre-A1': 'Can recognise familiar words/signs accompanied by pictures.',
      A1: 'Can understand very short, simple texts picking up familiar names, words and basic phrases.',
      A2: 'Can understand short, simple texts containing highest frequency vocabulary.',
      B1: 'Can read straightforward factual texts on subjects related to their field of interest.',
      B2: 'Can read with a large degree of independence, adapting style and speed.',
      C1: 'Can understand in detail lengthy, complex texts.',
      C2: 'Can understand virtually all forms of the written language including abstract texts.',
    },
  },
  {
    id: 'reading-correspondence',
    title: 'Reading Correspondence',
    skill: 'reading',
    category: 'Reception',
    descriptors: {
      A1: 'Can understand short, simple messages on postcards and via social media.',
      A2: 'Can understand short, simple personal letters.',
      B1: 'Can understand description of events and feelings in personal letters.',
      B2: 'Can read correspondence relating to their field of interest.',
      C1: 'Can understand any correspondence given occasional use of a dictionary.',
      C2: 'Can understand specialised correspondence outside their field with occasional dictionary use.',
    },
  },
  {
    id: 'reading-orientation',
    title: 'Reading for Orientation',
    skill: 'reading',
    category: 'Reception',
    descriptors: {
      A1: 'Can recognise familiar names, words/signs, and very basic phrases on simple notices.',
      A2: 'Can find specific, predictable information in simple everyday material.',
      B1: 'Can scan longer texts to locate desired information.',
      B2: 'Can scan quickly through long and complex texts, locating relevant details.',
      C1: 'Can search rapidly through several sources in parallel to find relevant information.',
    },
  },
  {
    id: 'reading-information-argument',
    title: 'Reading for Information & Argument',
    skill: 'reading',
    category: 'Reception',
    descriptors: {
      A1: 'Can get an idea of the content of simpler informational material.',
      A2: 'Can understand texts describing people, places, everyday life and culture.',
      B1: 'Can recognise significant points in straightforward news articles.',
      B2: 'Can understand articles with particular stances or viewpoints.',
      C1: 'Can understand in detail lengthy, complex texts in social, professional or academic life.',
      C2: 'Can understand the finer points and implications of a complex report or article.',
    },
  },
  {
    id: 'reading-instructions',
    title: 'Reading Instructions',
    skill: 'reading',
    category: 'Reception',
    descriptors: {
      A1: 'Can follow short, simple written directions.',
      A2: 'Can understand regulations expressed in simple language.',
      B1: 'Can understand clearly written instructions for a piece of equipment.',
      B2: 'Can understand lengthy, complex instructions in their field.',
      C1: 'Can understand in detail lengthy, complex instructions on a new machine or procedure.',
    },
  },
  {
    id: 'reading-leisure',
    title: 'Reading as a Leisure Activity',
    skill: 'reading',
    category: 'Reception',
    descriptors: {
      A1: 'Can understand short, illustrated narratives about everyday activities.',
      A2: 'Can understand short narratives and descriptions of someone\'s life in simple language.',
      B1: 'Can understand descriptions of places, events, feelings in narratives and magazines.',
      B2: 'Can read and appreciate contemporary literary texts.',
      C1: 'Can understand and appreciate sophisticated literary works of different periods and genres.',
      C2: 'Can appreciate fine distinctions of style and meaning in literary and non-literary texts.',
    },
  },
  // ===== RECEPTION STRATEGIES =====
  {
    id: 'identifying-cues-inferring',
    title: 'Identifying Cues & Inferring',
    skill: 'reading',
    category: 'Strategies',
    descriptors: {
      'Pre-A1': 'Can deduce the meaning of a word from an accompanying picture or icon.',
      A1: 'Can guess the probable meaning of an unknown word that is similar to one in their language.',
      A2: 'Can exploit format, appearance and typographic features to identify the type of text.',
      B1: 'Can make basic inferences or predictions about text content from headings and titles.',
      B2: 'Can use a variety of strategies to achieve comprehension, including contextual clues.',
      C1: 'Is skilled at using contextual, grammatical and lexical cues to infer attitude and mood.',
    },
  },
  // ===== PRODUCTION: ORAL =====
  {
    id: 'overall-oral-production',
    title: 'Overall Oral Production',
    skill: 'speaking',
    category: 'Production',
    descriptors: {
      'Pre-A1': 'Can produce short phrases about themselves, giving basic personal information.',
      A1: 'Can produce simple, mainly isolated phrases about people and places.',
      A2: 'Can give a simple description of people, living conditions, daily routines.',
      B1: 'Can reasonably fluently sustain a straightforward description within their field.',
      B2: 'Can give clear, detailed descriptions on a wide range of subjects.',
      C1: 'Can give clear, detailed descriptions on complex subjects, integrating sub-themes.',
      C2: 'Can produce clear, smoothly flowing, well-structured discourse.',
    },
  },
  {
    id: 'describing-experience',
    title: 'Sustained Monologue: Describing Experience',
    skill: 'speaking',
    category: 'Production',
    descriptors: {
      'Pre-A1': 'Can describe themselves using simple words and formulaic expressions.',
      A1: 'Can describe themselves, what they do and where they live.',
      A2: 'Can describe their family, living conditions, educational background.',
      B1: 'Can give straightforward descriptions on familiar subjects.',
      B2: 'Can give clear, detailed descriptions on subjects related to their field.',
      C1: 'Can give clear, detailed descriptions of complex subjects.',
      C2: 'Can give clear, smoothly flowing, elaborate and often memorable descriptions.',
    },
  },
  {
    id: 'giving-information',
    title: 'Sustained Monologue: Giving Information',
    skill: 'speaking',
    category: 'Production',
    descriptors: {
      A1: 'Can name an object and indicate its shape and colour.',
      A2: 'Can give simple directions on how to get from X to Y.',
      B1: 'Can report straightforward factual information on a familiar topic.',
      B2: 'Can communicate detailed information reliably.',
      C1: 'Can communicate clearly detailed distinctions between ideas, concepts and things.',
    },
  },
  {
    id: 'putting-a-case',
    title: 'Sustained Monologue: Putting a Case (Debate)',
    skill: 'speaking',
    category: 'Production',
    descriptors: {
      A2: 'Can present their opinion in simple terms, provided interlocutors are patient.',
      B1: 'Can briefly give reasons and explanations for opinions, plans and actions.',
      B2: 'Can develop a clear argument, expanding and supporting points of view.',
      C1: 'Can argue a case on a complex issue, formulating points precisely.',
      C2: 'Can argue a formal position convincingly, responding to questions and comments.',
    },
  },
  {
    id: 'addressing-audiences',
    title: 'Addressing Audiences',
    skill: 'speaking',
    category: 'Production',
    descriptors: {
      A1: 'Can read a very short, rehearsed statement.',
      A2: 'Can give a short, rehearsed presentation on a topic pertinent to their everyday life.',
      B1: 'Can give a prepared straightforward presentation on a familiar topic.',
      B2: 'Can give a clear, systematically developed presentation.',
      C1: 'Can give a clear, well-structured presentation of a complex subject.',
      C2: 'Can present a complex topic confidently and articulately to an audience.',
    },
  },
  // ===== PRODUCTION: WRITTEN =====
  {
    id: 'overall-written-production',
    title: 'Overall Written Production',
    skill: 'writing',
    category: 'Production',
    descriptors: {
      A1: 'Can write simple isolated phrases and sentences.',
      A2: 'Can write a series of simple phrases linked with simple connectors.',
      B1: 'Can write straightforward connected texts on familiar subjects.',
      B2: 'Can write clear, detailed texts on a variety of subjects.',
      C1: 'Can write clear, well-structured texts of complex subjects.',
      C2: 'Can write clear, smoothly flowing text in an appropriate style.',
    },
  },
  {
    id: 'creative-writing',
    title: 'Creative Writing',
    skill: 'writing',
    category: 'Production',
    descriptors: {
      A1: 'Can write simple phrases about themselves and imaginary people.',
      A2: 'Can write about everyday aspects of their environment in linked sentences.',
      B1: 'Can write straightforward, detailed descriptions on familiar subjects.',
      B2: 'Can write clear, detailed descriptions of real or imaginary events.',
      C1: 'Can write clear, detailed, well-structured descriptions and imaginative texts.',
      C2: 'Can write clear, smoothly flowing stories and descriptions in a style appropriate to genre.',
    },
  },
  {
    id: 'reports-essays',
    title: 'Reports & Essays',
    skill: 'writing',
    category: 'Production',
    descriptors: {
      A2: 'Can write very short, basic descriptions of events, past activities and personal experiences.',
      B1: 'Can write short, simple essays on topics of interest.',
      B2: 'Can write an essay or report that develops an argument systematically.',
      C1: 'Can write clear, well-structured expositions of complex subjects.',
      C2: 'Can produce clear, smoothly flowing, complex reports or articles which present a case.',
    },
  },
  // ===== INTERACTION: ORAL =====
  {
    id: 'overall-oral-interaction',
    title: 'Overall Oral Interaction',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      'Pre-A1': 'Can ask and answer questions about themselves and daily routines, using short formulaic expressions.',
      A1: 'Can interact in a simple way, dependent on repetition and rephrasing.',
      A2: 'Can communicate in simple and routine tasks requiring a direct exchange.',
      B1: 'Can exploit simple language to deal with most situations whilst travelling.',
      B2: 'Can interact with a degree of fluency and spontaneity.',
      C1: 'Can express themselves fluently and spontaneously, almost effortlessly.',
      C2: 'Can interact with ease, picking up and using non-verbal and intonational cues.',
    },
  },
  {
    id: 'understanding-interlocutor',
    title: 'Understanding an Interlocutor',
    skill: 'listening',
    category: 'Interaction',
    descriptors: {
      A1: 'Can understand everyday expressions aimed at the satisfaction of simple needs.',
      A2: 'Can understand enough to manage simple, routine exchanges without undue effort.',
      B1: 'Can follow clearly articulated language directed at them in everyday conversation.',
      B2: 'Can understand in detail what is said to them in the standard spoken language.',
      C1: 'Can understand enough to follow extended discourse on abstract topics.',
    },
  },
  {
    id: 'conversation',
    title: 'Conversation',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      A1: 'Can take part in a simple conversation on a predictable topic.',
      A2: 'Can handle very short social exchanges.',
      B1: 'Can enter unprepared into conversations on familiar topics.',
      B2: 'Can engage in extended conversation on most general topics.',
      C1: 'Can use language flexibly and effectively for social purposes.',
      C2: 'Can converse comfortably and appropriately, unhampered by any limitations.',
    },
  },
  {
    id: 'informal-discussion',
    title: 'Informal Discussion (Among Friends)',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      A2: 'Can discuss what to do, where to go and make arrangements.',
      B1: 'Can generally follow the main points in an informal discussion.',
      B2: 'Can take an active part in informal discussion in familiar contexts.',
      C1: 'Can easily follow and contribute to complex group discussions.',
      C2: 'Can hold their own in formal discussion of complex issues.',
    },
  },
  {
    id: 'formal-discussion',
    title: 'Formal Discussion (Meetings)',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      A2: 'Can express what they think about things when addressed directly in a formal meeting.',
      B1: 'Can take part in routine formal discussion of familiar subjects.',
      B2: 'Can follow the discussion on matters related to their field.',
      C1: 'Can keep up with an animated discussion, accurately identifying arguments.',
      C2: 'Can hold their own in formal discussion of complex issues.',
    },
  },
  {
    id: 'goal-oriented-cooperation',
    title: 'Goal-Oriented Co-operation',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      A1: 'Can understand questions and instructions and follow short, simple directions.',
      A2: 'Can communicate in simple and routine tasks using simple phrases.',
      B1: 'Can generally follow what is said and, when necessary, repeat back part of what someone has said.',
      B2: 'Can understand detailed instructions reliably.',
      C1: 'Can frame a discussion to decide on a course of action with a partner or group.',
    },
  },
  {
    id: 'obtaining-goods-services',
    title: 'Obtaining Goods & Services',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      'Pre-A1': 'Can make simple purchases when pointing or other gesture can support the verbal reference.',
      A1: 'Can ask people for things and give people things.',
      A2: 'Can ask for and provide everyday goods and services.',
      B1: 'Can deal with most transactions whilst travelling.',
      B2: 'Can cope linguistically to negotiate solutions to disputes.',
      C1: 'Can express themselves with clarity and precision, using language flexibly.',
    },
  },
  {
    id: 'information-exchange',
    title: 'Information Exchange',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      'Pre-A1': 'Can tell people their name and ask other people their names.',
      A1: 'Can understand simple questions and follow short directions.',
      A2: 'Can communicate in simple tasks using simple phrases.',
      B1: 'Can exchange, check and confirm factual information on familiar matters.',
      B2: 'Can understand and exchange complex information related to their role.',
      C1: 'Can easily follow and contribute to complex interactions.',
    },
  },
  {
    id: 'interviewing',
    title: 'Interviewing & Being Interviewed',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      A1: 'Can reply in an interview to simple direct questions spoken slowly and clearly.',
      A2: 'Can make themselves understood in an interview and communicate ideas and information.',
      B1: 'Can carry out a prepared interview, checking and confirming information.',
      B2: 'Can carry out an effective, fluent interview, departing from prepared questions.',
      C1: 'Can participate fully in an interview as either interviewer or interviewee.',
    },
  },
  {
    id: 'using-telecommunications',
    title: 'Using Telecommunications',
    skill: 'speaking',
    category: 'Interaction',
    descriptors: {
      A1: 'Can understand a request to call someone back and can give their phone number.',
      A2: 'Can make and receive phone calls on familiar topics.',
      B1: 'Can use the telephone to exchange information with the help of prepared notes.',
      B2: 'Can use the telephone for routine and non-routine matters.',
      C1: 'Can use the telephone for a variety of purposes with ease.',
    },
  },
  // ===== INTERACTION: WRITTEN =====
  {
    id: 'overall-written-interaction',
    title: 'Overall Written Interaction',
    skill: 'writing',
    category: 'Interaction',
    descriptors: {
      A1: 'Can ask for or pass on personal details in written form.',
      A2: 'Can write short, simple formulaic notes relating to matters of immediate need.',
      B1: 'Can convey information and ideas on abstract and concrete topics.',
      B2: 'Can express news and views effectively in writing.',
      C1: 'Can express themselves with clarity and precision in personal correspondence.',
      C2: 'Can write clear, smoothly flowing letters or messages on any subject.',
    },
  },
  {
    id: 'written-correspondence',
    title: 'Correspondence',
    skill: 'writing',
    category: 'Interaction',
    descriptors: {
      A1: 'Can write a short, simple postcard or online posting.',
      A2: 'Can write a short, simple letter or message to someone.',
      B1: 'Can write personal letters describing experiences and impressions.',
      B2: 'Can write letters highlighting the personal significance of events and experiences.',
      C1: 'Can express themselves with clarity and precision in personal correspondence.',
      C2: 'Can write appropriate and effective letters and other correspondence.',
    },
  },
  {
    id: 'notes-messages-forms',
    title: 'Notes, Messages & Forms',
    skill: 'writing',
    category: 'Interaction',
    descriptors: {
      A1: 'Can fill in a simple registration form with basic personal details.',
      A2: 'Can take a short, simple message provided they can ask for repetition.',
      B1: 'Can write notes conveying simple information of immediate relevance.',
      B2: 'Can take messages communicating enquiries, explaining problems.',
    },
  },
  {
    id: 'online-interaction',
    title: 'Online Interaction',
    skill: 'writing',
    category: 'Interaction',
    descriptors: {
      A1: 'Can post simple online greetings using basic formulaic expressions.',
      A2: 'Can make short descriptive online postings about everyday matters.',
      B1: 'Can post a comprehensible contribution in an online discussion on a familiar topic.',
      B2: 'Can engage in online interaction, linking contributions to previous ones.',
      C1: 'Can follow and contribute to complex online interaction, adjusting register.',
      C2: 'Can participate effectively in live online professional or academic discussion.',
    },
  },
  // ===== MEDIATION =====
  {
    id: 'relaying-information',
    title: 'Relaying Specific Information',
    skill: 'reading',
    category: 'Mediation',
    descriptors: {
      A1: 'Can relay simple, predictable information about times, places, numbers.',
      A2: 'Can relay specific, relevant information contained in clearly structured short texts.',
      B1: 'Can relay specific information given in straightforward texts on familiar subjects.',
      B2: 'Can relay detailed information and messages reliably.',
      C1: 'Can explain the relevance of specific information found in a particular section of a text.',
    },
  },
  {
    id: 'explaining-data',
    title: 'Explaining Data',
    skill: 'reading',
    category: 'Mediation',
    descriptors: {
      A1: 'Can convey simple, predictable information in a list or simple chart.',
      A2: 'Can describe simple graphs or diagrams (e.g. a pie chart).',
      B1: 'Can describe and compare data using visual supports.',
      B2: 'Can interpret and present reliably detailed information from charts and graphs.',
      C1: 'Can interpret and present clearly and reliably complex data and trends.',
    },
  },
  {
    id: 'processing-text',
    title: 'Processing Text',
    skill: 'reading',
    category: 'Mediation',
    descriptors: {
      A2: 'Can pick out and reproduce key words and phrases from a short text.',
      B1: 'Can collate short pieces of information from several sources and summarise them.',
      B2: 'Can summarise a wide range of factual and imaginative texts.',
      C1: 'Can summarise long, demanding texts.',
      C2: 'Can provide a summary suitable for a specific audience.',
    },
  },
  {
    id: 'translating-text',
    title: 'Translating a Written Text',
    skill: 'writing',
    category: 'Mediation',
    descriptors: {
      A1: 'Can convey simple, predictable information about themselves or needs in simple terms.',
      A2: 'Can convey the main point(s) of clearly written, short, simple texts.',
      B1: 'Can provide an approximate translation of short passages on familiar subjects.',
      B2: 'Can translate general texts, paraphrasing the intentions of the source text.',
      C1: 'Can translate texts on specialised topics, conveying the intent faithfully.',
    },
  },
  {
    id: 'note-taking',
    title: 'Note-Taking (Lectures, Seminars, Meetings)',
    skill: 'writing',
    category: 'Mediation',
    descriptors: {
      A2: 'Can note down the time and date of the next meeting.',
      B1: 'Can take notes of key points during a straightforward talk on a familiar subject.',
      B2: 'Can take detailed notes during a lecture on topics in their field.',
      C1: 'Can understand a complex lecture, making notes of the points made.',
    },
  },
  {
    id: 'personal-response-creative',
    title: 'Expressing Personal Response to Creative Texts',
    skill: 'reading',
    category: 'Mediation',
    descriptors: {
      A1: 'Can use simple words to state how a work made them feel.',
      A2: 'Can express their reactions to a work, reporting feelings and ideas in simple language.',
      B1: 'Can explain which character they most identified with and why.',
      B2: 'Can relate themes and characters in a work to their own experience and explain connections.',
      C1: 'Can give a personal interpretation of a work, exploring possible meanings.',
      C2: 'Can give a critical appraisal of work of different periods and genres.',
    },
  },
  {
    id: 'analysis-criticism-creative',
    title: 'Analysis & Criticism of Creative Texts',
    skill: 'reading',
    category: 'Mediation',
    descriptors: {
      A2: 'Can identify and briefly describe key themes and characters in simple narratives.',
      B1: 'Can point out the most important episodes and events in a narrative.',
      B2: 'Can compare two works, considering themes, characters and scenes.',
      C1: 'Can critically appraise a wide variety of texts including literary works.',
      C2: 'Can give a critical appraisal appreciating subtle distinctions of style and meaning.',
    },
  },
  // ===== MEDIATION: CONCEPTS =====
  {
    id: 'facilitating-collaboration',
    title: 'Facilitating Collaborative Interaction',
    skill: 'speaking',
    category: 'Mediation',
    descriptors: {
      A1: 'Can invite others\' contributions to very simple tasks using short phrases.',
      A2: 'Can collaborate in simple, practical tasks, asking what others think.',
      B1: 'Can invite other people in a group to contribute their views.',
      B2: 'Can ask questions to stimulate discussion on how to organise collaborative work.',
      C1: 'Can show sensitivity to different perspectives within a group.',
    },
  },
  {
    id: 'collaborating-meaning',
    title: 'Collaborating to Construct Meaning',
    skill: 'speaking',
    category: 'Mediation',
    descriptors: {
      A1: 'Can express an idea and ask what others think, using very simple words.',
      A2: 'Can make simple remarks and pose occasional questions to indicate they are following.',
      B1: 'Can repeat part of what someone has said to confirm mutual understanding.',
      B2: 'Can further develop other people\'s ideas and opinions.',
      C1: 'Can frame a discussion to decide on a course of action, weighing up multiple points of view.',
      C2: 'Can summarise, evaluate and link contributions to facilitate agreement.',
    },
  },
  {
    id: 'managing-interaction',
    title: 'Managing Interaction',
    skill: 'speaking',
    category: 'Mediation',
    descriptors: {
      A2: 'Can give very simple instructions to a co-operative group.',
      B1: 'Can give simple, clear instructions to organise an activity.',
      B2: 'Can explain ground rules of collaborative discussion in small groups.',
      C1: 'Can organise a varied sequence of plenary, group and individual work.',
      C2: 'Can take on different roles according to the needs of participants.',
    },
  },
  {
    id: 'encouraging-conceptual-talk',
    title: 'Encouraging Conceptual Talk',
    skill: 'speaking',
    category: 'Mediation',
    descriptors: {
      A2: 'Can ask what somebody thinks of a certain idea.',
      B1: 'Can ask appropriate questions to check understanding of a concept.',
      B2: 'Can formulate questions and feedback to encourage people to expand on their thinking.',
      C1: 'Can ask a series of open questions to stimulate logical reasoning.',
      C2: 'Can effectively lead the development of ideas in discussion of complex abstract topics.',
    },
  },
  // ===== MEDIATION: COMMUNICATION =====
  {
    id: 'facilitating-pluricultural',
    title: 'Facilitating Pluricultural Space',
    skill: 'speaking',
    category: 'Mediation',
    descriptors: {
      A1: 'Can facilitate simple exchanges using their limited repertoire.',
      A2: 'Can help create a shared communication culture.',
      B1: 'Can support a multicultural exchange using their expanding repertoire.',
      B2: 'Can act as mediator in intercultural encounters, explaining misunderstandings.',
      C1: 'Can mediate effectively and naturally between members of different cultures.',
    },
  },
  {
    id: 'acting-intermediary',
    title: 'Acting as Intermediary',
    skill: 'speaking',
    category: 'Mediation',
    descriptors: {
      A1: 'Can convey very basic information (e.g. numbers, names) between speakers of different languages.',
      A2: 'Can communicate the main point of what is said in predictable everyday situations.',
      B1: 'Can act as intermediary in routine situations, relaying simple information.',
      B2: 'Can act as intermediary in informal discussions with some complexity.',
      C1: 'Can mediate effectively between speakers, taking account of sociocultural differences.',
    },
  },
  // ===== COMPETENCES: LINGUISTIC =====
  {
    id: 'general-linguistic-range',
    title: 'General Linguistic Range',
    skill: 'grammar',
    category: 'Competences',
    descriptors: {
      A1: 'Has a very basic range of simple expressions about personal details and needs.',
      A2: 'Has a basic language repertoire and strategies to deal with predictable situations.',
      B1: 'Has enough language to get by, with sufficient vocabulary for topics of interest.',
      B2: 'Has a sufficient range of language to describe unpredictable situations.',
      C1: 'Can select an appropriate formulation from a broad range of language.',
      C2: 'Can exploit a comprehensive and reliable mastery of a very wide range of language.',
    },
  },
  {
    id: 'vocabulary-range',
    title: 'Vocabulary Range',
    skill: 'vocabulary',
    category: 'Competences',
    descriptors: {
      A1: 'Has a very basic range of simple expressions about personal details.',
      A2: 'Has sufficient vocabulary for basic communicative needs.',
      B1: 'Has sufficient vocabulary to express themselves with some circumlocutions.',
      B2: 'Has a good range of vocabulary for matters connected to their field.',
      C1: 'Has a good command of a broad lexical repertoire.',
      C2: 'Has a good command of a very broad lexical repertoire including colloquial and idiomatic expressions.',
    },
  },
  {
    id: 'vocabulary-control',
    title: 'Vocabulary Control',
    skill: 'vocabulary',
    category: 'Competences',
    descriptors: {
      A2: 'Can control a narrow repertoire dealing with concrete everyday needs.',
      B1: 'Shows good control of elementary vocabulary.',
      B2: 'Lexical accuracy is generally high.',
      C1: 'Occasional minor slips, but no significant vocabulary errors.',
      C2: 'Consistently correct and appropriate use of vocabulary.',
    },
  },
  {
    id: 'grammatical-accuracy',
    title: 'Grammatical Accuracy',
    skill: 'grammar',
    category: 'Competences',
    descriptors: {
      A1: 'Shows only limited control of a few simple grammatical structures.',
      A2: 'Uses some simple structures correctly, but still makes basic mistakes.',
      B1: 'Communicates with reasonable accuracy in familiar contexts.',
      B2: 'Shows a relatively high degree of grammatical control.',
      C1: 'Consistently maintains a high degree of grammatical accuracy.',
      C2: 'Maintains consistent grammatical control of complex language.',
    },
  },
  {
    id: 'phonological-control',
    title: 'Phonological Control & Pronunciation',
    skill: 'speaking',
    category: 'Competences',
    descriptors: {
      A1: 'Pronunciation of a very limited repertoire can be understood with some effort.',
      A2: 'Pronunciation is generally clear enough to be understood.',
      B1: 'Pronunciation is clearly intelligible even if a foreign accent is sometimes evident.',
      B2: 'Has acquired a clear, natural pronunciation and intonation.',
      C1: 'Can vary intonation and place sentence stress correctly.',
      C2: 'Can employ the full range of phonological features in the target language.',
    },
  },
  {
    id: 'orthographic-control',
    title: 'Orthographic Control & Spelling',
    skill: 'writing',
    category: 'Competences',
    descriptors: {
      A1: 'Can copy familiar words and short phrases.',
      A2: 'Can write short words with reasonable accuracy.',
      B1: 'Can produce writing which is generally intelligible. Spelling and punctuation are mostly accurate.',
      B2: 'Can produce clearly intelligible writing following standard conventions.',
      C1: 'Layout and punctuation are consistent and helpful. Spelling is accurate.',
      C2: 'Writing is orthographically free of error.',
    },
  },
  // ===== COMPETENCES: SOCIOLINGUISTIC =====
  {
    id: 'sociolinguistic-appropriateness',
    title: 'Sociolinguistic Appropriateness',
    skill: 'speaking',
    category: 'Competences',
    descriptors: {
      A1: 'Can use simplest everyday polite forms of greetings and farewells.',
      A2: 'Can handle very short social exchanges using everyday polite forms.',
      B1: 'Can perform and respond to a wide range of language functions in a neutral register.',
      B2: 'Can express themselves confidently in a formal or informal register.',
      C1: 'Can recognise a wide range of idiomatic expressions and colloquialisms.',
      C2: 'Can mediate effectively and naturally, adopting a role according to the needs.',
    },
  },
  // ===== COMPETENCES: PRAGMATIC =====
  {
    id: 'flexibility',
    title: 'Flexibility',
    skill: 'speaking',
    category: 'Competences',
    descriptors: {
      A1: 'No descriptors available for this level.',
      A2: 'Can adapt well-rehearsed simple phrases to particular circumstances.',
      B1: 'Can adapt their expression to deal with less routine situations.',
      B2: 'Can adjust what they say and the means of expressing it to the situation.',
      C1: 'Can modify their expression flexibly to fit the context.',
      C2: 'Shows great flexibility reformulating ideas in differing linguistic forms.',
    },
  },
  {
    id: 'turn-taking',
    title: 'Turn-Taking',
    skill: 'speaking',
    category: 'Competences',
    descriptors: {
      A1: 'No descriptors available.',
      A2: 'Can use simple techniques to start, maintain, or end a short conversation.',
      B1: 'Can intervene in a discussion on a familiar topic, using a suitable phrase.',
      B2: 'Can initiate, maintain and end discourse naturally with effective turn-taking.',
      C1: 'Can select a suitable phrase to preface their remarks to get the floor.',
      C2: 'Can interact with ease, picking up and using non-verbal and intonational cues.',
    },
  },
  {
    id: 'thematic-development',
    title: 'Thematic Development',
    skill: 'writing',
    category: 'Competences',
    descriptors: {
      A1: 'No descriptors available.',
      A2: 'Can tell a story or describe something in a simple list of points.',
      B1: 'Can reasonably fluently relate a straightforward narrative or description.',
      B2: 'Can develop a clear description or narrative, expanding and supporting main points.',
      C1: 'Can give elaborate descriptions and narratives, integrating sub-themes.',
      C2: 'Can give an effective, logical, well-structured discourse.',
    },
  },
  {
    id: 'coherence-cohesion',
    title: 'Coherence & Cohesion',
    skill: 'writing',
    category: 'Competences',
    descriptors: {
      A1: 'Can link words with very basic connectors like "and" or "then".',
      A2: 'Can link groups of words with simple connectors.',
      B1: 'Can link shorter elements into a connected sequence of points.',
      B2: 'Can use a variety of linking words efficiently.',
      C1: 'Can produce clear, smoothly flowing, well-structured text with controlled use of cohesive devices.',
      C2: 'Can create coherent and cohesive text making full and appropriate use of organisational patterns.',
    },
  },
  {
    id: 'propositional-precision',
    title: 'Propositional Precision',
    skill: 'writing',
    category: 'Competences',
    descriptors: {
      A1: 'Can communicate basic information about personal details in a simple way.',
      A2: 'Can communicate what they want to say in a simple and direct exchange.',
      B1: 'Can convey simple, straightforward information of immediate relevance.',
      B2: 'Can pass on detailed information reliably.',
      C1: 'Can qualify opinions and statements precisely in relation to degrees of certainty.',
      C2: 'Can convey finer shades of meaning precisely using a wide range of qualifying devices.',
    },
  },
  {
    id: 'fluency',
    title: 'Fluency',
    skill: 'speaking',
    category: 'Competences',
    descriptors: {
      'Pre-A1': 'Can manage very short, isolated, rehearsed utterances using gesture.',
      A1: 'Can manage very short, isolated, mainly pre-packaged utterances.',
      A2: 'Can construct phrases on familiar topics with sufficient ease to handle short exchanges.',
      B1: 'Can keep going comprehensibly, even though pausing for planning is evident.',
      B2: 'Can produce stretches of language with a fairly even tempo.',
      C1: 'Can express themselves fluently and spontaneously, almost effortlessly.',
      C2: 'Can express themselves at length with a natural, effortless, unhesitating flow.',
    },
  },
];
